language: node_js

before_install:
  - sudo apt-get install ffmpeg

node_js:
  - "6"

script:
  - yarn test
  - yarn backend:coverage-travis -- -v

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest yarn
  - yarn
  - cp ./secure.json.template ./secure.json
