language: node_js

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

dist: trusty
sudo: required

node_js:
  - "7"

script:
  - yarn test
  # - yarn backend:coverage-travis -- -v

install:
  - npm install
  - cp ./secure.json.template ./secure.json
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -q
  - sudo apt-get install ffmpeg -y
  - ffmpeg -version
  - ffprobe -version
